=== emubox-cli/apps/apps/_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$id": "https://emubox-cli.github.io/apps/_schema.json",
    "title": "Emubox App",
    "description": "Linux app data for an emulator",
    "type": "object",
    "if": {
        "contains": {
            "properties": {
                "extends": { "type": "string" }
            }
        }
    },
    "then": {
        "required": ["name", "installOptions", "$schema"]
    },
    "else": {
        "required": ["name", "consoles", "gameExec", "romQuery", "postInstall", "needsBios", "flags", "$schema"]
    },
    "properties": {
        "extends": {
            "description": "Name of other app file to pull base info from.\nThis exists because of Yuzu and Ryujinx having various revival forks.",
            "type": "string"
        },
        "name": {
            "description": "Name of application",
            "type": "string"
        },
        
        "consoles": {
            "description": "List of consoles the app supports.\n\nPlease confirm your console name matches one of the following: https://github.com/emubox-cli/app/blob/4ec7e910d78b05b2413ab825bc9413de9354596b/src/utils/apps.ts#L4",
            "type": "array"
        },
        "needsBios": {
            "description": "If emulator requires BIOS before playing",
            "type": "boolean"
        },
        "gameExec": {
            "description": "String of arguments to run a game in this emulator in fullscreen (or just run it)\n\nuse `{}` in place of the rom path",
            "type": "string"
        },
        "romQuery": {
            "description": "Regex string to match rom names for their consoles.",
            "type": "string"
        },
        "flags": {
            "type": "object"
        },
        "postInstall": {
            "description": "Files and directories to initialize after install.\n\nPlaceholders:\n<save> = `$HOME/.emubox/saves`\n<config> = `$HOME/.emubox/.config`\n<share> = `$HOME/.emubox/.local/share`",
            "required": ["makeLinks", "makeDirs", "makeFiles"],
            "type": "object",
            "properties": {
                "makeLinks": {
                    "description": "Object of paths to make symlinks for; Key is where the link will be made, Value is the reference path.",
                    "type": "object"
                },
                "makeDirs": {
                    "description": "List of directories to make.",
                    "type": "array"
                },
                "makeFiles": {
                    "description": "List of files to make, along with their content.\nEmubox will automatically convert any json input into the correct file-type.",
                    "type": "array",
                    "required": ["path", "content"],
                    "properties": {
                        "path": {
                            "description": "Path to file, suffix will be used to determine how file content will be formatted",
                            "type": "string"
                        },
                        "content": {
                            "description": "File contents in json format.",
                            "type": "object"
                        }
                    }
                }
            }
        },
        "installOptions": {
            "required": [],
            "properties": {
                "aur": {
                    "description": "[DEPRECATED] The AUR repo this emulator can be installed at.",
                    "type": "string"
                },
                "aurExportName": {
                    "description": "[DEPRECATED] The app name for `distrobox-export`, necessary if it differs from the AUR install name.",
                    "type": "string"
                },
                "flatpak": {
                    "description": "The flatpak id this emulator can be installed at.",
                    "type": "string"
                },
                "gitRepo": {
                    "description": "The `<repo>/<name>` this emulator has releases at on github.",
                    "type": "string"
                },
                "gitRe": {
                    "description": "The regex string to search for a release asset under.",
                    "type": "string"
                }
            }
        }
    }
}

=== emubox-cli/apps/apps/rpcs3.json
{
    "name": "RPCS3",
    "consoles": ["ps3"],
    "gameExec": "--no-gui {}",
    "romQuery": ".*",
    "needsBios": true,
    "flags": {},
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [],
        "makeFiles": []
    },
    "installOptions": {
        "flatpak": "net.rpcs3.RPCS3",
        "aur": "rpcs3-git",
        "aurExportName": "rpcs3",
        "gitRepo": "RPCS3/rpcs3-binaries-linux",
        "gitRe": "rpcs3-v.*-.*-.*_linux64.AppImage"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/cemu.json
{
    "name": "Cemu",
    "consoles": ["wiiu"],
    "gameExec": "-g {}",
    "needsBios": false,
    "flags": {},
    "romQuery": ".*(.wud|.WUD|.wux|.WUX|.wua|.WUA|.wuhb|.WUHB|.iso|.ISO|.rpx|.RPX|.elf|.ELF)",
    "postInstall": {
        "makeDirs": [],
        "makeFiles": [],
        "makeLinks": {}
    },
    "installOptions": {
        "flatpak": "info.cemu.Cemu",
        "aur": "cemu-git",
        "aurExportName": "Cemu",
        "gitRepo": "cemu-project/Cemu",
        "gitRe": "Cemu-.*-x86_64.AppImage"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/pcsx2.json
{
    "name": "PCSX2",
    "consoles": ["ps2"],
    "gameExec": "{fullscreen} -- {}",
    "romQuery": ".*(.bin|.BIN|.chd|.CHD|.cso|.CSO|.dump|.DUMP|.gz|.GZ|.img|.IMG|.iso|.ISO|.mdf|.MDF|.nrg|.NRG)",
    "needsBios": true,
    "flags": {
        "fullscreen": "-fullscreen"
    },
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [],
        "makeFiles": []
    },
    "installOptions": {
        "flatpak": "net.pcsx2.PCSX2",
        "aur": "pcsx2-git",
        "aurExportName": "PCSX2",
        "aurBin": "pcsx2-qt",
        "gitRepo": "pcsx2/pcsx2",
        "gitRe": "pcsx2-v.*-linux-appimage-x64-Qt.AppImage",
        "libretroCore": "pcsx2"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/dolphin-emu.json
{
    "name": "Dolphin Emulator",
    "consoles": ["gc", "wii"],
    "gameExec": "-b -e {}",
    "romQuery": ".*(.ciso|.CISO|.dol|.DOL|.elf|.ELF|.gcm|.GCM|.gcz|.GCZ|.iso|.ISO|.nkit.iso|.NKIT.ISO|.rvz|.RVZ|.wad|.WAD|.wia|.WIA)",
    "needsBios": false,
    "flags": {},
    "postInstall": {
        "makeLinks": {
            "<mods>/<id>/Load": "<config>/dolphin-emu/Load"
        },
        "makeDirs": [
            "<config>/dolphin-emu",
            "<save>/dolphin-emu/GC/USA",
            "<save>/dolphin-emu/GC/EUR",
            "<save>/dolphin-emu/GC/JPN",
            "<save>/dolphin-emu/GC/JAP",
            "<save>/dolphin-emu/Wii"
        ],
        "makeFiles": [{
            "path": "<config>/dolphin-emu/Dolphin.ini",
            "content": {
                "Core": {
                    "GCIFolderAPath": "<save>/dolphin-emu/GC"
                },
                "General": {
                    "NANDRootPath": "<save>/dolphin-emu/Wii"
                }
            }
        }]
    },
    "installOptions": {
        "flatpak": "org.DolphinEmu.dolphin-emu",
        "aur": "dolphin-emu-git",
        "aurExportName": "dolphin-emu",
        "libretroCore": "dolphin",
        "gitRepo": "pkgforge-dev/Dolphin-emu-AppImage",
        "gitRe": "Dolphin_Emulator-.*-anylinux.squashfs-x86_64.AppImage"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/ryujinx.json
{
    "name": "Ryujinx (Ryubing)",
    "consoles": ["switch"],
    "gameExec": "{}",
    "romQuery": ".*(.kip|.KIP|.nca|.NCA|.nro|.NRO|.nso|.NSO|.nsp|.NSP|.xci|.XCI)",
    "needsBios": true,
    "flags": {},
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [],
        "makeFiles": []
    },
    "installOptions": {
        "flatpak": "io.github.ryubing.Ryujinx",
        "aur": "ryujinx-git",
        "aurExportName": "ryujinx",
        "gitRepo": "ryubing/ryujinx",
        "gitRe": "ryujinx-*.-x64.AppImage"
    },
    "$schema": "./_schema.json"
}

=== emubox-cli/apps/apps/duckstation.json
{
    "name": "DuckStation",
    "consoles": ["psx"],
    "gameExec": "{fullscreen} -- {}",
    "romQuery": ".*(.bin|.BIN|.img|.IMG|.iso|.ISO|.cue|.CUE|.chd|.CHD|.cpe|.CPE|.ecm|.ECM|.mds|.MDS|.pbp|.PBP|.elf|.ELF|.exe|.EXE|.psexe|.PSEXE|.ps-exe|.PS-EXE|.psx|.PSX|.psf|.PSF|.minipsf|.MINIPSF|.m3u|.M3U|.psxgpu|.PSXGPU)",
    "needsBios": true,
    "flags": {
        "fullscreen": "-fullscreen"
    },
    "postInstall": {
        "makeLinks": {
            "<bios>/<id>": "<config>/duckstation/bios"
        },
        "makeDirs": [
            "<config>/duckstation"
        ],
        "makeFiles": [{
            "path": "<config>/duckstation/settings.ini",
            "content": {
                "GameList": {
                    "RecursivePaths": "<roms>/psx"
                }
            }
        }]
    },
    "installOptions": {
        "flatpak": "org.duckstation.DuckStation",
        "aur": "duckstation-git",
        "aurExportName": "duckstation",
        "gitRepo": "stenzek/duckstation",
        "gitRe": "DuckStation-x64.AppImage"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/ryujinx-legacy.json
{
    "name": "Ryujinx (Legacy)",
    "consoles": ["switch"],
    "gameExec": "{}",
    "romQuery": ".*",
    "needsBios": true,
    "flags": {},
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [],
        "makeFiles": []
    },
    "installOptions": {
        "flatpak": "org.ryujinx.Ryujinx",
        "manual": true
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/snes9x.json
{
    "name": "Snes9x",
    "consoles": ["snes"],
    "gameExec": "{}",
    "romQuery": ".*(.smc|.SMC|.sfc|.SFC|.swc|.SWC)",
    "needsBios": false,
    "flags": {},
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [
            "<config>/snes9x",
            "<save>/snes9x/saves",
            "<save>/snes9x/states"
        ],
        "makeFiles": [
            {
                "path": "<config>/snes9x/snes9x.conf",
                "content": {
                    "Files": {
                        "SRAMDirectory": "<save>/snes9x/saves",
                        "SaveStateDirectory": "<save>/snes9x/states"
                    },
                    "Sound": {
                        "Driver": "3"
                    }
                }
            }
        ]
    },
    "installOptions": {
        "flatpak": "com.snes9x.Snes9x",
        "flatpakOverrideFs": true,
        "aur": "snes9x-gtk-git",
        "aurExportName": "snes9x-gtk",
        "libretroCore": "snes9x",
        "gitRepo": "snes9xgit/snes9x",
        "gitRe": "Snes9x-.*-x86_64.AppImage"
    },
    "$schema": "_schema.json" 
}
