=== emubox-cli/apps/apps/_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$id": "https://emubox-cli.github.io/apps/_schema.json",
    "title": "Emubox App",
    "description": "Linux app data for an emulator",
    "type": "object",
    "if": {
        "contains": {
            "properties": {
                "extends": { "type": "string" }
            }
        }
    },
    "then": {
        "required": ["name", "installOptions", "$schema"]
    },
    "else": {
        "required": ["name", "consoles", "gameExec", "romQuery", "postInstall", "needsBios", "flags", "$schema"]
    },
    "properties": {
        "extends": {
            "description": "Name of other app file to pull base info from.\nThis exists because of Yuzu and Ryujinx having various revival forks.",
            "type": "string"
        },
        "name": {
            "description": "Name of application",
            "type": "string"
        },
        
        "consoles": {
            "description": "List of consoles the app supports.\n\nPlease confirm your console name matches one of the following: https://github.com/emubox-cli/app/blob/4ec7e910d78b05b2413ab825bc9413de9354596b/src/utils/apps.ts#L4",
            "type": "array"
        },
        "needsBios": {
            "description": "If emulator requires BIOS before playing",
            "type": "boolean"
        },
        "gameExec": {
            "description": "String of arguments to run a game in this emulator in fullscreen (or just run it)\n\nuse `{}` in place of the rom path",
            "type": "string"
        },
        "romQuery": {
            "description": "Regex string to match rom names for their consoles.",
            "type": "string"
        },
        "flags": {
            "type": "object"
        },
        "postInstall": {
            "description": "Files and directories to initialize after install.\n\nPlaceholders:\n<save> = `$HOME/.emubox/saves`\n<config> = `$HOME/.emubox/.config`\n<share> = `$HOME/.emubox/.local/share`",
            "required": ["makeLinks", "makeDirs", "makeFiles"],
            "type": "object",
            "properties": {
                "makeLinks": {
                    "description": "Object of paths to make symlinks for; Key is where the link will be made, Value is the reference path.",
                    "type": "object"
                },
                "makeDirs": {
                    "description": "List of directories to make.",
                    "type": "array"
                },
                "makeFiles": {
                    "description": "List of files to make, along with their content.\nEmubox will automatically convert any json input into the correct file-type.",
                    "type": "array",
                    "required": ["path", "content"],
                    "properties": {
                        "path": {
                            "description": "Path to file, suffix will be used to determine how file content will be formatted",
                            "type": "string"
                        },
                        "content": {
                            "description": "File contents in json format.",
                            "type": "object"
                        }
                    }
                }
            }
        },
        "installOptions": {
            "required": [],
            "properties": {
                "aur": {
                    "description": "[DEPRECATED] The AUR repo this emulator can be installed at.",
                    "type": "string"
                },
                "aurExportName": {
                    "description": "[DEPRECATED] The app name for `distrobox-export`, necessary if it differs from the AUR install name.",
                    "type": "string"
                },
                "flatpak": {
                    "description": "The flatpak id this emulator can be installed at.",
                    "type": "string"
                },
                "gitRepo": {
                    "description": "The `<repo>/<name>` this emulator has releases at on github.",
                    "type": "string"
                },
                "gitRe": {
                    "description": "The regex string to search for a release asset under.",
                    "type": "string"
                }
            }
        }
    }
}

=== emubox-cli/apps/apps/rmg.json
{
    "name": "Rosalie's Mupen GUI",
    "consoles": ["n64"],
    "gameExec": "{fullscreen} {}",
    "romQuery": ".*(.n64|.N64|.z64|.Z64|.v64|.V64|.ndd|.NDD|.d64|.D64|.zip|.ZIP|.7z|.7Z)",
    "needsBios": false,
    "flags": {
        "fullscreen": "-f"
    },
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [
            "<config>/RMG",
            "<save>/rmg/saves",
            "<save>/rmg/states"
            
        ],
        "makeFiles": [{
            "path": "<config>/RMG/mupen64plus.cfg",
            "content": {
                "Core": {
                    "SaveSRAMPath": "\"<save>/rmg/saves\"",
                    "SavesStatePath": "\"<save>/rmg/states\""
                }
            }
        }]
    },
    "installOptions": {
        "flatpak": "com.github.Rosalie241.RMG",
        "aur": "rmg-git",
        "aurExportName": "RMG",
        "gitRepo": "rosalie241/rmg",
        "gitRe": "RMG-Portable-Linux64-v.*.AppImage"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/mgba.json
{
    "name": "mGBA",
    "consoles": ["gba"],
    "gameExec": "{fullscreen} {}",
    "romQuery": ".*(.7z|.7Z|.gba|.GBA|.zip|.ZIP)",
    "needsBios": false,
    "flags": {
        "fullscreen": "-f"
    },
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [
            "<config>/mgba",
            "<save>/mgba/saves",
            "<save>/mgba/states"
        ], 
        "makeFiles": [{
            "path": "<config>/mgba/config.ini",
            "content": {
                "ports.qt": {
                    "savegamePath": "<save>/mgba/saves",
                    "savestatePath": "<save>/mgba/states"
                }
            }
        }]
    },
    "installOptions": {
        "flatpak": "io.mgba.mGBA",
        "aur": "mgba-qt-git",
        "aurExportName": "mgba-qt",
        "gitRepo": "mgba-emu/mgba",
        "gitRe": "mGBA-.*-appimage-x64.appimage",
        "libretroCore": "mgba"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/ppsspp.json
{
    "name": "PPSSPP",
    "consoles": ["psp"],
    "gameExec": "{fullscreen} {}",
    "romQuery": ".*",
    "needsBios": false,
    "flags": {
        "fullscreen": "-f"
    },
    "postInstall": {
        "makeLinks": {},
        "makeDirs": [],
        "makeFiles": []
    },
    "installOptions": {
        "flatpak": "org.ppsspp.PPSSPP",
        "aur": "ppsspp-git",
        "aurExportName": "PPSSPPSDL",
        "libretroCore": "ppsspp",
        "gitRepo": "pkgforge-dev/PPSSPP-AppImage",
        "gitRe": "ppsspp-.*-anylinux-x86_64.AppImage"
    },
    "$schema": "_schema.json"
}

=== emubox-cli/apps/apps/melonds.json
{
    "name": "MelonDS",
    "consoles": ["nds"],
    "gameExec": "{fullscreen} {}",
    "romQuery": ".*(.7z|.7Z|.nds|.NDS|.zip|.ZIP)",
    "needsBios": false,
    "flags": {
        "fullscreen": "-f"
    },
    "postInstall": {
        "makeLinks": {
            
        },
        "makeDirs": [
            "<config>/melonDS",
            "<save>/melonds/saves",
            "<save>/melonds/states"
        ],
        
        "makeFiles": [{
            "path": "<config>/melonDS/melonDS.toml",
            "content": {
                "Instance0": {
                    "SaveFilePath": "\"<save>/melonds/saves\"",
                    "SavestatePath": "\"<save>/melonds/saves\""
                }
            }
        }]
    },
    "installOptions": {
        "flatpak": "net.kuribo64.melonDS",
        "aur": "melonds-git",
        "aurExportName": "melonDS",
        "gitRepo": "melonds-emu/melonds",
        "gitRe": "melonDS-appimage-x86_64.zip",
        "unzipTarget": "melonDS-x86_64.AppImage",
        "libretroCore": "melonds"
    },
    "$schema": "_schema.json" 
}
